### ISSUE TITLE
meta archive will cause the entire archive pipeline to end prematurely

### ISSUE THREAD

**Issue by renzhexigua** [goreleaser/goreleaser#3803]
### What happened?

The archive node with `meta: true` will cause other archive nodes immediately following it to be ignored/skipped in the case of **multiple archives**.

### How can we reproduce this?

```yaml
...snip...

archives:
  - id: common
    builds:
      - common
    meta: true # hereeeeeee you can change the order of node `common` and node `others` to test 
    name_template: "{{ .ProjectName }}_{{ .Version }}_common"
    files:
      - src: "docs/*"

  - id: others
    builds:
      - others
    files:
      - src: "docs/*"

...snip...
```

I create a MRE repo at [renzhexigua/goreleaser_meta_issue](https://github.com/renzhexigua/goreleaser_meta_issue) that inclues two commits.

- 1st commit: [goreleaser_meta_issue@fd42f5b](https://github.com/renzhexigua/goreleaser_meta_issue/commit/fd42f5bb7b8f1dbf04185a6fa2c2728be94ba221) will only produce one tar.gz archive under the `dist` folder:
  - common.tar.gz
- 2nd commit: [goreleaser_meta_issue@1c54d61](https://github.com/renzhexigua/goreleaser_meta_issue/commit/1c54d614192e18f72346c932174c3cc052f654f0) that changes the order of archive pipeline will generate all combinations:
  - common.tar.gz
  - darwin_amd64.tar.gz
  - darwi_arm64.tar.gz
  - windows_386.tar.gz
  - ...

### goreleaser version

```bash
goreleaser version dev
goos: linux
goarch: amd64
module version: v1.15.2, checksum: h1:VYCFKTzzZFnFfSqfjvOmT8ip7VcZv1Y9JV13hAuDDB8=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I guess the reason for this bug may be in the following place:

https://github.com/goreleaser/goreleaser/blob/702164076d57408472e38742083d47e5569325c4/internal/pipe/archive/archive.go#L94-L96

When the runner encounters an archive.node with `meta: true` property, it will return directly.

While the runner is using goroutine to handle other archives:

https://github.com/goreleaser/goreleaser/blob/702164076d57408472e38742083d47e5569325c4/internal/pipe/archive/archive.go#L112-L127

**Comment by caarlos0** [comment]
ouch, good catch!

**Comment by eyevanovich** [comment]
Nice! I just came across this same issue.
