### ISSUE TITLE
multi-language todo list

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#5327]
- [ ] support for [cargo publish](https://doc.rust-lang.org/cargo/reference/publishing.html)
- [ ] more examples in the documentation
- [ ] example repositories for rust
- [ ] change `builds.*.gobinary` to something like `builds.*.toolbinary` (or something else more generic)
- [ ] move flag processing to a common package?

**Comment by caarlos0** [comment]
refs #5325 #5312

**Comment by caarlos0** [comment]
updated all example repos, added topics, descriptions, etc

**Comment by jon4hz** [comment]
Hey there,
Amazing to see that we can use goreleaser for other languages too now! Do you already have plans for other languages beside rust and zig? I'd love to use goreleaser for some python projects I'm currently working on.
